from PHX.model import project
from PHX.to_WUFI_XML.xml_builder import generate_WUFI_XML_from_object
from tests.test_to_WUFI_xml._utils import xml_string_to_list


def test_default_PhxProject(reset_class_counters):
    v1 = project.PhxVariant()
    print("remarks=", v1.remarks)
    result = generate_WUFI_XML_from_object(v1, _header="")
    assert xml_string_to_list(result) == [
        "<IdentNr>1</IdentNr>",
        "<Name>unnamed_variant</Name>",
        "<Remarks/>",
        "<Graphics_3D>",
        '<Vertices count="0"/>',
        '<Polygons count="0"/>',
        "</Graphics_3D>",
        "<Building>",
        '<Components count="0"/>',
        '<Zones count="0"/>',
        "</Building>",
        "<ClimateLocation>",
        "<Selection>2</Selection>",
        '<Latitude_DB unit="°">40.6</Latitude_DB>',
        '<Longitude_DB unit="°">-73.8</Longitude_DB>',
        '<HeightNN_DB unit="m"/>',
        "<dUTC_DB>-4</dUTC_DB>",
        '<Albedo choice="User defined">-2</Albedo>',
        '<GroundReflShort unit="-">0.2</GroundReflShort>',
        '<GroundReflLong unit="-">0.1</GroundReflLong>',
        '<GroundEmission unit="-">0.9</GroundEmission>',
        '<CloudIndex unit="-">0.66</CloudIndex>',
        '<CO2concenration unit="mg/m³">350</CO2concenration>',
        '<Unit_CO2concentration choice="ppmv">48</Unit_CO2concentration>',
        "<PH_ClimateLocation>",
        "<Selection>6</Selection>",
        "<DailyTemperatureSwingSummer>8.0</DailyTemperatureSwingSummer>",
        "<AverageWindSpeed>4.0</AverageWindSpeed>",
        "<Latitude>40.6</Latitude>",
        "<Longitude>-73.8</Longitude>",
        "<HeightNNWeatherStation>3.0</HeightNNWeatherStation>",
        "<dUTC>-4</dUTC>",
        "<HeightNNBuilding/>",
        "<ClimateZone>1</ClimateZone>",
        "<GroundThermalConductivity>2.0</GroundThermalConductivity>",
        "<GroundHeatCapacitiy>1000.0</GroundHeatCapacitiy>",
        "<GroundDensity>2000.0</GroundDensity>",
        "<DepthGroundwater>3.0</DepthGroundwater>",
        "<FlowRateGroundwater>0.05</FlowRateGroundwater>",
        '<TemperatureMonthly count="0"/>',
        '<DewPointTemperatureMonthly count="0"/>',
        '<SkyTemperatureMonthly count="0"/>',
        '<NorthSolarRadiationMonthly count="0"/>',
        '<EastSolarRadiationMonthly count="0"/>',
        '<SouthSolarRadiationMonthly count="0"/>',
        '<WestSolarRadiationMonthly count="0"/>',
        '<GlobalSolarRadiationMonthly count="0"/>',
        "<TemperatureHeating1>0.0</TemperatureHeating1>",
        "<NorthSolarRadiationHeating1>0.0</NorthSolarRadiationHeating1>",
        "<EastSolarRadiationHeating1>0.0</EastSolarRadiationHeating1>",
        "<SouthSolarRadiationHeating1>0.0</SouthSolarRadiationHeating1>",
        "<WestSolarRadiationHeating1>0.0</WestSolarRadiationHeating1>",
        "<GlobalSolarRadiationHeating1>0.0</GlobalSolarRadiationHeating1>",
        "<TemperatureHeating2>0.0</TemperatureHeating2>",
        "<NorthSolarRadiationHeating2>0.0</NorthSolarRadiationHeating2>",
        "<EastSolarRadiationHeating2>0.0</EastSolarRadiationHeating2>",
        "<SouthSolarRadiationHeating2>0.0</SouthSolarRadiationHeating2>",
        "<WestSolarRadiationHeating2>0.0</WestSolarRadiationHeating2>",
        "<GlobalSolarRadiationHeating2>0.0</GlobalSolarRadiationHeating2>",
        "<TemperatureCooling>0.0</TemperatureCooling>",
        "<NorthSolarRadiationCooling>0.0</NorthSolarRadiationCooling>",
        "<EastSolarRadiationCooling>0.0</EastSolarRadiationCooling>",
        "<SouthSolarRadiationCooling>0.0</SouthSolarRadiationCooling>",
        "<WestSolarRadiationCooling>0.0</WestSolarRadiationCooling>",
        "<GlobalSolarRadiationCooling>0.0</GlobalSolarRadiationCooling>",
        "<TemperatureCooling2>0.0</TemperatureCooling2>",
        "<NorthSolarRadiationCooling2>0.0</NorthSolarRadiationCooling2>",
        "<EastSolarRadiationCooling2>0.0</EastSolarRadiationCooling2>",
        "<SouthSolarRadiationCooling2>0.0</SouthSolarRadiationCooling2>",
        "<WestSolarRadiationCooling2>0.0</WestSolarRadiationCooling2>",
        "<GlobalSolarRadiationCooling2>0.0</GlobalSolarRadiationCooling2>",
        "<SelectionPECO2Factor>6</SelectionPECO2Factor>",
        '<PEFactorsUserDef count="16">',
        '<PEF0 unit="kWh/kWh">1.1</PEF0>',
        '<PEF1 unit="kWh/kWh">1.1</PEF1>',
        '<PEF2 unit="kWh/kWh">1.1</PEF2>',
        '<PEF3 unit="kWh/kWh">1.1</PEF3>',
        '<PEF4 unit="kWh/kWh">0.2</PEF4>',
        '<PEF5 unit="kWh/kWh">1.8</PEF5>',
        '<PEF6 unit="kWh/kWh">0.7</PEF6>',
        '<PEF7 unit="kWh/kWh">0.8</PEF7>',
        '<PEF8 unit="kWh/kWh">1.1</PEF8>',
        '<PEF9 unit="kWh/kWh">1.5</PEF9>',
        '<PEF10 unit="kWh/kWh">0.7</PEF10>',
        '<PEF11 unit="kWh/kWh">1.1</PEF11>',
        '<PEF12 unit="kWh/kWh">1.5</PEF12>',
        '<PEF13 unit="kWh/kWh">0.8</PEF13>',
        '<PEF14 unit="kWh/kWh">1.1</PEF14>',
        '<PEF15 unit="kWh/kWh">1.5</PEF15>',
        "</PEFactorsUserDef>",
        '<CO2FactorsUserDef count="16">',
        '<CO2F0 unit="g/kWh">309.9966</CO2F0>',
        '<CO2F1 unit="g/kWh">250.0171</CO2F1>',
        '<CO2F2 unit="g/kWh">270.0102</CO2F2>',
        '<CO2F3 unit="g/kWh">439.9864</CO2F3>',
        '<CO2F4 unit="g/kWh">53.4289</CO2F4>',
        '<CO2F5 unit="g/kWh">680.0068</CO2F5>',
        '<CO2F6 unit="g/kWh">250.0171</CO2F6>',
        '<CO2F7 unit="g/kWh">239.9864</CO2F7>',
        '<CO2F8 unit="g/kWh">319.9932</CO2F8>',
        '<CO2F9 unit="g/kWh">409.9966</CO2F9>',
        '<CO2F10 unit="g/kWh">-70.0102</CO2F10>',
        '<CO2F11 unit="g/kWh">129.9898</CO2F11>',
        '<CO2F12 unit="g/kWh">319.9932</CO2F12>',
        '<CO2F13 unit="g/kWh">100</CO2F13>',
        '<CO2F14 unit="g/kWh">250.0171</CO2F14>',
        '<CO2F15 unit="g/kWh">409.9966</CO2F15>',
        "</CO2FactorsUserDef>",
        "</PH_ClimateLocation>",
        "</ClimateLocation>",
        "<PassivehouseData>",
        "<PH_CertificateCriteria>7</PH_CertificateCriteria>",
        "<PH_SelectionTargetData>2</PH_SelectionTargetData>",
        "<AnnualHeatingDemand>15.0</AnnualHeatingDemand>",
        "<AnnualCoolingDemand>15.0</AnnualCoolingDemand>",
        "<PeakHeatingLoad>10.0</PeakHeatingLoad>",
        "<PeakCoolingLoad>10.0</PeakCoolingLoad>",
        '<PH_Buildings count="1">',
        '<PH_Building index="0">',
        "<IdentNr>1</IdentNr>",
        "<BuildingCategory>1</BuildingCategory>",
        "<OccupancyTypeResidential>1</OccupancyTypeResidential>",
        "<BuildingStatus>1</BuildingStatus>",
        "<BuildingType>1</BuildingType>",
        "<OccupancySettingMethod>2</OccupancySettingMethod>",
        "<NumberUnits>1</NumberUnits>",
        "<CountStories>1</CountStories>",
        "<EnvelopeAirtightnessCoefficient>1.0</EnvelopeAirtightnessCoefficient>",
        "<SummerHRVHumidityRecovery>4</SummerHRVHumidityRecovery>",
        '<FoundationInterfaces count="0"/>',
        "<InternalGainsAdditionalData>",
        '<EvaporationHeatPerPerson unit="W">15</EvaporationHeatPerPerson>',
        "<HeatLossFluschingWC>true</HeatLossFluschingWC>",
        "<QuantityWCs>1</QuantityWCs>",
        "<RoomCategory>1</RoomCategory>",
        "<UseDefaultValuesSchool>false</UseDefaultValuesSchool>",
        "<MarginalPerformanceRatioDHW/>",
        "</InternalGainsAdditionalData>",
        "<MechanicalRoomTemperature>20.0</MechanicalRoomTemperature>",
        "<IndoorTemperature>20.0</IndoorTemperature>",
        "<OverheatingTemperatureThreshold>25.0</OverheatingTemperatureThreshold>",
        "<NonCombustibleMaterials>false</NonCombustibleMaterials>",
        "</PH_Building>",
        "</PH_Buildings>",
        "<UseWUFIMeanMonthShading>true</UseWUFIMeanMonthShading>",
        "</PassivehouseData>",
        "<HVAC>",
        '<Systems count="1">',
        '<System index="0">',
        "<Name>Ideal Air System</Name>",
        '<Type choice="User defined (ideal system)">1</Type>',
        "<IdentNr>1</IdentNr>",
        '<ZonesCoverage count="1">',
        '<ZoneCoverage index="0">',
        "<IdentNrZone>1</IdentNrZone>",
        "<CoverageHeating>1.0</CoverageHeating>",
        "<CoverageCooling>1.0</CoverageCooling>",
        "<CoverageVentilation>1.0</CoverageVentilation>",
        "<CoverageHumidification>1.0</CoverageHumidification>",
        "<CoverageDehumidification>1.0</CoverageDehumidification>",
        "</ZoneCoverage>",
        "</ZonesCoverage>",
        '<Devices count="0"/>',
        "<PHDistribution>",
        "<DistributionDHW>",
        "<CalculationMethodIndividualPipes>4</CalculationMethodIndividualPipes>",
        "<DemandRecirculation>true</DemandRecirculation>",
        "<SelectionhotWaterFixtureEff>1</SelectionhotWaterFixtureEff>",
        "<NumberOfBathrooms>1</NumberOfBathrooms>",
        "<AllPipesAreInsulated>true</AllPipesAreInsulated>",
        "<SelectionUnitsOrFloors>2</SelectionUnitsOrFloors>",
        "<PipeMaterialSimplifiedMethod>2</PipeMaterialSimplifiedMethod>",
        "<PipeDiameterSimplifiedMethod>25.4</PipeDiameterSimplifiedMethod>",
        "<TemperatureRoom_WR>20.0</TemperatureRoom_WR>",
        "<DesignFlowTemperature_WR>60.0</DesignFlowTemperature_WR>",
        "<DailyRunningHoursCirculation_WR>0.0</DailyRunningHoursCirculation_WR>",
        "<LengthCirculationPipes_WR>0</LengthCirculationPipes_WR>",
        "<HeatLossCoefficient_WR/>",
        "<LengthIndividualPipes_WR>0</LengthIndividualPipes_WR>",
        "<ExteriorPipeDiameter_WR/>",
        '<Truncs count="0"/>',
        "</DistributionDHW>",
        "<DistributionCooling/>",
        '<DistributionVentilation count="0"/>',
        "<UseDefaultValues>false</UseDefaultValues>",
        "<DeviceInConditionedSpace>true</DeviceInConditionedSpace>",
        '<SupportiveDevices count="0"/>',
        "</PHDistribution>",
        "</System>",
        "</Systems>",
        "</HVAC>",
    ]
